---
title: "owner-analysis"
format: html
author: Maggie Harings
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
here()


```

```{r}
lobster_abundance <- read_csv(here("data/Lobster_Abundance_All_Years_20220829.csv"))
```

```{r}
# convert missing values to NA
lobster_abundance.NAs <- lobster_abundance %>% 
  mutate(SIZE_MM = case_when(
    SIZE_MM == -99999 ~ NA_real_,
    TRUE ~ SIZE_MM
  ))
    
```

```{r}
# filtering practice
lobster.abund.noNAPL <- lobster_abundance.NAs %>% 
  filter(SITE != "NAPL")

# make sure this worked
table(unique(lobster.abund.noNAPL) %in% "NAPL")   # shouldn't all be 'FALSE'

# create data subset: lobsters from AQUE w/carapace lenght > 70 mm
lobs.aque.70 <- lobster.abund.noNAPL %>% 
  filter(SITE == "AQUE" & SIZE_MM > 70)

# make sure this worked
sort(unique(lobs.aque.70$SITE))
sort(unique(lobs.aque.70$SIZE_MM))

# max carapace length
(lobs.aque.70.max <- lobs.aque.70 %>% 
  group_by(SITE, MONTH) %>% 
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE)))


```

## Exercise: Data Visualization

```{r}
# PLOT: lobster carapace length

(plot_carapaceLength <- ggplot(lobster_abundance.NAs,
                              aes(x = SIZE_MM)) +
   geom_histogram() +
   facet_wrap(~SITE))
```
```{r}

# group data by site and year
lobster.site.year <- lobster_abundance.NAs %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

# PLOT: lobsters observed by year

(plot_lobstersPerYear <- ggplot(lobster.site.year,
                              aes(x = YEAR,
                                  y = COUNT)) +
   geom_line(aes(color=SITE)) +
  geom_line(aes(color = SITE)))     
```

```{r}
# filter 2019-2021
lobster_size_lrg <- lobster_abundance.NAs %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, "small", "large")) %>%
  group_by(SITE, SIZE_BIN) %>% 
  summarize(COUNT = n()) %>% 
  drop_na()
  
# PLOT: bar graph
(plot_largeSmall <- ggplot(lobster_size_lrg,
                              aes(x = SITE,
                                  y = COUNT,
                                  fill = SIZE_BIN)) +
    geom_col(position = "dodge") +
    # add line at y=0
        geom_hline(yintercept = 0, 
               color = "white",
               size = 2) +
    # modify axes, legend titles
    labs(x = "Site",
         y = "Count",
         fill = "Size bin",
         title = "Ugly plot of lobster counts!") +
    # modify legend contents
    scale_fill_discrete(labels = c("Small (<=70 mm)", "Large >70 mm)")) +
    theme_classic() +
    theme(
      # make background purple
      panel.background = element_rect(fill = "purple"),
    ) +
    # add random asterisk
    annotate(
      "text",
      x = "AQUE",  
      y = .5 *max(lobster_size_lrg$COUNT),      # vertical position
      label = "*",                              # add asterisk
      color = "white",                          # make asterisk white
      size = 20                                 # enlarge asterisk
    )
  )

# save world's ugliest plot
ggsave("../figs/wordsUgliestPlot.jpg",
       plot_largeSmall)
# ggsave(here("figs/wordsUgliestPlot"))

```

